function ark=d4(ark,or,i,j,k)
p=or(i+8,j);q=or(i+8,j+4);x=or(i+8,j)-or(i+4,j+4);y=or(i+8,j+4)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i+4,j);q=or(i+8,j);x=or(i+4,j)-or(i+4,j+4);y=or(i+8,j)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i,j);q=or(i+4,j);x=or(i,j)-or(i+4,j+4);y=or(i+4,j)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i,j+4);q=or(i,j);x=or(i,j+4)-or(i+4,j+4);y=or(i,j)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i,j+8);q=or(i,j+4);x=or(i,j+8)-or(i+4,j+4);y=or(i,j+4)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i+4,j+8);q=or(i,j+8);x=or(i+4,j+8)-or(i+4,j+4);y=or(i,j+8)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i+8,j+8);q=or(i+4,j+8);x=or(i+8,j+8)-or(i+4,j+4);y=or(i+4,j+8)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    
p=or(i+8,j+4);q=or(i+8,j+8);x=or(i+8,j+4)-or(i+4,j+4);y=or(i+8,j+8)-or(i+4,j+4);
if((p-((x./y).*q))>=0)
    ark(k)=1;k=k+1;
else
    ark(k)=0;k=k+1;
end    